<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'comments';

    //指定主键
    protected $primaryKey = 'id';

    //指定不允许批量赋值的字段
    protected $guarded = [];

    //自动维护时间戳 新增数据时会对数据表中 字段为 create_at 和 update_at 的数据自动格式化
    public $timestamps = false;

    //返回时间戳
    protected function getDateFormat()
    {
        return time(); // 直接返回时间戳
    }

    //防止格式化时间戳
    protected function asDateTime($value)
    {
        //return parent::asDateTime($value); // TODO: Change the autogenerated stub
        return $value;
    }


}
